/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#d6c3b2",
        "inverse-primary": "#855300",
        "primary-fixed-dim": "#ffb960",
        "tertiary-container": "#ac9f8e",
        "on-primary": "#472a00",
        "surface-container": "#251e1a",
        "on-primary-fixed-variant": "#653e00",
        "on-secondary-container": "#faaf69",
        "surface": "#19120e",
        "error": "#ffb4ab",
        "outline-variant": "#514537",
        "outline": "#9e8e7e",
        "surface-container-low": "#211a16",
        "secondary": "#ffb876",
        "on-tertiary-fixed-variant": "#4f4538",
        "surface-tint": "#ffb960",
        "on-tertiary": "#372f22",
        "inverse-on-surface": "#372f2a",
        "surface-container-highest": "#3c332e",
        "surface-variant": "#3c332e",
        "error-container": "#93000a",
        "surface-container-lowest": "#130d09",
        "on-secondary-fixed": "#2d1600",
        "surface-dim": "#19120e",
        "on-tertiary-container": "#3f3629",
        "on-secondary": "#4b2800",
        "on-background": "#eee0d9",
        "surface-container-high": "#302824",
        "tertiary": "#d2c4b2",
        "on-primary-container": "#513100",
        "primary-container": "#d4943f",
        "secondary-fixed-dim": "#ffb876",
        "background": "#19120e",
        "on-error": "#690005",
        "primary": "#ffb960",
        "on-secondary-fixed-variant": "#6b3b00",
        "inverse-surface": "#eee0d9",
        "on-primary-fixed": "#2a1700",
        "secondary-container": "#754100",
        "tertiary-fixed-dim": "#d2c4b2",
        "surface-bright": "#403733",
        "primary-fixed": "#ffddb8",
        "secondary-fixed": "#ffdcc0",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#221a0f",
        "on-surface": "#eee0d9",
        "tertiary-fixed": "#efe0cd"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
